### ISSUE TITLE
Add compability to Wagtail 3

### ISSUE THREAD

**Issue by marteinn** [rinti/wagtail-meta-preview#4]
I'm noticing the error `'BoundPanel' object has no attribute 'template_name'` when trying to use the package in Wagtail 3. Probably related to the EditHandler -> Panel refactoring here: https://github.com/wagtail/wagtail/blob/main/wagtail/admin/panels.py

**Comment by marteinn** [comment]
PR here: https://github.com/rinti/wagtail-meta-preview/pull/5

**Comment by rinti** [comment]
Closed in https://github.com/rinti/wagtail-meta-preview/pull/5
